language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
install:
  - pip install pytest ./
before_script:
  - psql -U postgres -c 'CREATE DATABASE "test";'
  - psql -U postgres -c 'CREATE USER jrandom SUPERUSER;'
script: 
  - ./runtests.sh
branches:
  only:
    - master
notifications:
  email: false
  irc: false
