language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - "nightly"

matrix:
  allow_failures:
  - python: "nightly"

addons:
  postgresql: 9.6
install:
  - pip install tox-travis
before_script:
  - psql -U postgres -c 'CREATE DATABASE "test";'
script:
  - tox
branches:
  only:
    - master
notifications:
  email: false
  irc: false
