language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
install:
  - pip install --use-mirrors pytest ./
before_script:
  - psql -U postgres -c 'CREATE DATABASE "test";'
  - psql -U postgres -c 'CREATE USER jrandom SUPERUSER;'
script: 
  - ./runtests.sh
notifications:
  email: false
  irc: 
    channels:
      - "irc.freenode.org#gittip"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true

