language: python
python:
  - 2.6
  - 2.7
  - 3.0
  - 3.1
  - 3.2
  - 3.3
  - 3.4
install:
  - python setup.py -q install
  - pip install --use-mirrors pytest
before_script:
  - psql -U postgres -c 'CREATE DATABASE "test";'
script: DATABASE_URL=postgres://postgres@localhost/test py.test tests.py -v
notifications:
  email: false
  irc: 
    channels:
      - "irc.freenode.org#gittip"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true

