language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
addons:
  postgresql: 9.6
install:
  - pip install pytest ./
before_script:
  - psql -U postgres -c 'CREATE DATABASE "test";'
  - psql -U postgres -c 'CREATE USER jrandom SUPERUSER;'
script:
  - ./runtests.sh
branches:
  only:
    - master
notifications:
  email: false
  irc: false
